language: node_js
node_js: 12
jdk: oraclejdk8
sudo: required
dist: bionic
cache:
  directories:
  - "$HOME/.npm"
notifications:
  slack:
    - rooms:
      - secure: W7oVtyosuG/53P4sZXDWxWNwpMiU8/jywOaeaIUcbyFKFx0itObV1ENwbd+8f0Lftfe8kAzxIq3MoH76L+G58AbGPnBmuaD2VWTAqeX2ij+/fk6I9eHf8pxFFh+0EX9bGFfE9y1ICU757p4zFYEwthFxoFnjE9Adw6n85A8MRCJ2uLX7htXSIm8l+2h3YuJN/nJb6FVESx1waTy5h2g3NeziD0MFvOvF6+iCNYWpzQGrXQZd08aTI9LyZkoA8dmTTN3s6BWSXESbamzmYiUbaRYJNixX7wE0vzu7qcwfhUzP8tlSQ8dowz7MxUfUuK3lWBYSlksWu4nQ5+Me2Fe6YjjPjeF94x7KAGf61mM8AN/Djwq/8btHUhuXwUSIcdg5EPybcwaIvmvyLEJ6mpIw78y4hN7xzL7IGTybrpCFNZZS1M+YgStQuos/eVXPHP9yHORv/1YNJI2iTeaIUgoabM147OB1e7wG8UtnM16+D9b1gyhlufkzzAJjFvKjAF0eHl0Hj1o9q0+UIiyMalK2PvE8TvFdzJMn3wC/elbCNCNXdRHKaVKfflM1eShRxczqBpr+O7ZqvbS/PoxdtqNFB/2wnZzlcsfV95U36n+d7VmRmi2alem/q3mp4PYNNIxF6ayG/RsbUiAhPfo40rNSHs8s6asdmvwbfEiVo2oue+8=
      if: type=push && TRAVIS_JOB_NAME="Push"
      on_success: always
      on_failure: always
      template:
        - "Push Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
    - rooms:
      - secure: W7oVtyosuG/53P4sZXDWxWNwpMiU8/jywOaeaIUcbyFKFx0itObV1ENwbd+8f0Lftfe8kAzxIq3MoH76L+G58AbGPnBmuaD2VWTAqeX2ij+/fk6I9eHf8pxFFh+0EX9bGFfE9y1ICU757p4zFYEwthFxoFnjE9Adw6n85A8MRCJ2uLX7htXSIm8l+2h3YuJN/nJb6FVESx1waTy5h2g3NeziD0MFvOvF6+iCNYWpzQGrXQZd08aTI9LyZkoA8dmTTN3s6BWSXESbamzmYiUbaRYJNixX7wE0vzu7qcwfhUzP8tlSQ8dowz7MxUfUuK3lWBYSlksWu4nQ5+Me2Fe6YjjPjeF94x7KAGf61mM8AN/Djwq/8btHUhuXwUSIcdg5EPybcwaIvmvyLEJ6mpIw78y4hN7xzL7IGTybrpCFNZZS1M+YgStQuos/eVXPHP9yHORv/1YNJI2iTeaIUgoabM147OB1e7wG8UtnM16+D9b1gyhlufkzzAJjFvKjAF0eHl0Hj1o9q0+UIiyMalK2PvE8TvFdzJMn3wC/elbCNCNXdRHKaVKfflM1eShRxczqBpr+O7ZqvbS/PoxdtqNFB/2wnZzlcsfV95U36n+d7VmRmi2alem/q3mp4PYNNIxF6ayG/RsbUiAhPfo40rNSHs8s6asdmvwbfEiVo2oue+8=
      if: type=pull_request
      on_success: always
      on_failure: always
      template:
        - "Pull Request Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
    - rooms:
      - secure: W7oVtyosuG/53P4sZXDWxWNwpMiU8/jywOaeaIUcbyFKFx0itObV1ENwbd+8f0Lftfe8kAzxIq3MoH76L+G58AbGPnBmuaD2VWTAqeX2ij+/fk6I9eHf8pxFFh+0EX9bGFfE9y1ICU757p4zFYEwthFxoFnjE9Adw6n85A8MRCJ2uLX7htXSIm8l+2h3YuJN/nJb6FVESx1waTy5h2g3NeziD0MFvOvF6+iCNYWpzQGrXQZd08aTI9LyZkoA8dmTTN3s6BWSXESbamzmYiUbaRYJNixX7wE0vzu7qcwfhUzP8tlSQ8dowz7MxUfUuK3lWBYSlksWu4nQ5+Me2Fe6YjjPjeF94x7KAGf61mM8AN/Djwq/8btHUhuXwUSIcdg5EPybcwaIvmvyLEJ6mpIw78y4hN7xzL7IGTybrpCFNZZS1M+YgStQuos/eVXPHP9yHORv/1YNJI2iTeaIUgoabM147OB1e7wG8UtnM16+D9b1gyhlufkzzAJjFvKjAF0eHl0Hj1o9q0+UIiyMalK2PvE8TvFdzJMn3wC/elbCNCNXdRHKaVKfflM1eShRxczqBpr+O7ZqvbS/PoxdtqNFB/2wnZzlcsfV95U36n+d7VmRmi2alem/q3mp4PYNNIxF6ayG/RsbUiAhPfo40rNSHs8s6asdmvwbfEiVo2oue+8=
      if: type=cron && branch=master && TRAVIS_JOB_NAME="Cron1"
      on_success: always
      on_failure: always
      template:
        - "Nightly Build (Cron1) <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}  by %{author} %{result} in %{duration}"
    - rooms:
      - secure: W7oVtyosuG/53P4sZXDWxWNwpMiU8/jywOaeaIUcbyFKFx0itObV1ENwbd+8f0Lftfe8kAzxIq3MoH76L+G58AbGPnBmuaD2VWTAqeX2ij+/fk6I9eHf8pxFFh+0EX9bGFfE9y1ICU757p4zFYEwthFxoFnjE9Adw6n85A8MRCJ2uLX7htXSIm8l+2h3YuJN/nJb6FVESx1waTy5h2g3NeziD0MFvOvF6+iCNYWpzQGrXQZd08aTI9LyZkoA8dmTTN3s6BWSXESbamzmYiUbaRYJNixX7wE0vzu7qcwfhUzP8tlSQ8dowz7MxUfUuK3lWBYSlksWu4nQ5+Me2Fe6YjjPjeF94x7KAGf61mM8AN/Djwq/8btHUhuXwUSIcdg5EPybcwaIvmvyLEJ6mpIw78y4hN7xzL7IGTybrpCFNZZS1M+YgStQuos/eVXPHP9yHORv/1YNJI2iTeaIUgoabM147OB1e7wG8UtnM16+D9b1gyhlufkzzAJjFvKjAF0eHl0Hj1o9q0+UIiyMalK2PvE8TvFdzJMn3wC/elbCNCNXdRHKaVKfflM1eShRxczqBpr+O7ZqvbS/PoxdtqNFB/2wnZzlcsfV95U36n+d7VmRmi2alem/q3mp4PYNNIxF6ayG/RsbUiAhPfo40rNSHs8s6asdmvwbfEiVo2oue+8=
      if: type=cron && branch=master && TRAVIS_JOB_NAME="Cron2"
      on_success: always
      on_failure: always
      template:
        - "Nightly Build (Cron2) <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}  by %{author} %{result} in %{duration}"
    - rooms:
      - secure: W7oVtyosuG/53P4sZXDWxWNwpMiU8/jywOaeaIUcbyFKFx0itObV1ENwbd+8f0Lftfe8kAzxIq3MoH76L+G58AbGPnBmuaD2VWTAqeX2ij+/fk6I9eHf8pxFFh+0EX9bGFfE9y1ICU757p4zFYEwthFxoFnjE9Adw6n85A8MRCJ2uLX7htXSIm8l+2h3YuJN/nJb6FVESx1waTy5h2g3NeziD0MFvOvF6+iCNYWpzQGrXQZd08aTI9LyZkoA8dmTTN3s6BWSXESbamzmYiUbaRYJNixX7wE0vzu7qcwfhUzP8tlSQ8dowz7MxUfUuK3lWBYSlksWu4nQ5+Me2Fe6YjjPjeF94x7KAGf61mM8AN/Djwq/8btHUhuXwUSIcdg5EPybcwaIvmvyLEJ6mpIw78y4hN7xzL7IGTybrpCFNZZS1M+YgStQuos/eVXPHP9yHORv/1YNJI2iTeaIUgoabM147OB1e7wG8UtnM16+D9b1gyhlufkzzAJjFvKjAF0eHl0Hj1o9q0+UIiyMalK2PvE8TvFdzJMn3wC/elbCNCNXdRHKaVKfflM1eShRxczqBpr+O7ZqvbS/PoxdtqNFB/2wnZzlcsfV95U36n+d7VmRmi2alem/q3mp4PYNNIxF6ayG/RsbUiAhPfo40rNSHs8s6asdmvwbfEiVo2oue+8=
      if: type=cron && branch!=master
      on_success: always
      on_failure: always
      template:
        - "Cron Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}  by %{author} %{result} in %{duration}"
before_script:
- npm install mocha
- npm -v
- node -v
- ls
jobs:
  include:
  - script:
    if: type=push
    name: Push
    script:
      - npm -v
      - echo "Push"
  - script:
    if: type=cron
    name: Cron1
    script:
      - npm -v
      - echo "Cron1"
  - script:
    if: type=cron
    name: Cron2
    script:
      - npm -v
      - echo "Cron2"
  - script:
    if: type=pull_request
    name: PR
    script:
      - npm -v
      - echo "Pull Request"