os: osx
env:
  global:
  - CXX=g++
language: node_js
node_js:
- 10
jdk:
- oraclejdk8
before_script:
# - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_retry npm install -g eslint; fi
# - brew install yarn
# - npm install -g eslint
# - npm install -g jasmine-core
# - npm install -g karma
# - npm install -g karma-coverage
# - npm install -g karma-jasmine
# - npm install -g karma-jasmine-jquery
# - npm install -g karma-phantomjs-launcher
# - npm install -g sfdx-cli
script:
- node -v
- echo "Which error log are you checking today? "
  read answer
  if [ -f /opt/logs/$answer*.errors ]
      then
          if [ -s /opt/logs/$answer*.errors ]
              then
                  echo "Content is present in the $answer error log file."
              else
                  echo "No errors are present in the $answer error log file."
          fi
      else
          echo "$answer does not have an error log at this time."
  fi
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]];
      then
          if [[ sfdx force:lightning:test:install22 ]];
              then
                  echo "install OK";
              else
                  npm install -g eslint;
          fi
      else
            echo "install Failed";
  fi
# - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_retry npm install -g eslint; fi
# - if [[ "$TRAVIS_PULL_REQUEST" = "true" ]]; then
#     npm install -g sfdx-cli ;
#   fi