language:        node_js
node_js:         12
jdk:             oraclejdk8
sudo:            required
dist:            bionic
cache:
  directories:
    - $HOME/.npm
jobs:
  if: type=push
    include:
      - script:
        name: "test1"
        script:
        - npm -v
      - script:
        name: "test2"
        script:
        - npm -v
