language:        node_js
node_js:         12
jdk:             oraclejdk8
sudo:            required
dist:            bionic
cache:
  directories:
    - $HOME/.npm
jobs:
  include:
    - script:
      if: type=push
      name: "test1"
      script:
      - npm -v
    - script:
      if: type=cron
      name: "test2"
      script:
      - npm -v
