# This is a basic workflow to help you get started with Actions

name: CRON
env:
  pr_labels: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/2 * * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world! || echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Get PR labels
      run: 'curl https://api.github.com/repos/chendagit/aws/pulls/${{env.pr_labels}} > pr_labels.json'
    - name: Show PR json result
      run: cat pr_labels.json
    - name: PR labels
      run: node ./js/should-it-build.js
