name: Manually triggered workflow 2 other branch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'test 1'
        required: true
        default: 'test'
      home:
        description: 'location'
        required: false
        default: 'test2'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: workflows
      - run: git status