name: On all actions
on:
  workflow_dispatch:
    inputs:
        name:
          description: 'Person to greet'
          required: true
          default: 'Mona the Octocat'
        home:
          description: 'location'
          required: false
          default: 'The Octoverse'
  pull_request:
    type: [labeled]
  schedule:
    - cron: '1/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo 'Hello, world!'