name: On all actions - test
on:
  workflow_dispatch:
    inputs:
          suites:
            description: 'Test suites'
            required: true
            default: 'templates'
  pull_request:
  schedule:
    - cron: '1/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Run a one-line script
        run: |
          echo 'Hello, world!'
          echo "github inputs - description : ${{ github.event.inputs.suites }}"
          npm install
          npm install -g $(echo "${{ github.event.inputs.suites }}")