name: CI
on: [pull_request, push]
  pull_request:
    types: [ edited, synchronize ]
  workflow_dispatch:
env:
      LABELS: ${{ toJson(github.event.pull_request.labels.*.description) }}
      LABELS2: ${{ toJson(github.event.action) }}
jobs:
  build:
    # if: ${{ github.event.action == 'labeled' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PR labels 2
      if: contains(github.event.pull_request.labels.*.name, 'BatchJobs')
      run: echo 'Test 2 pr label is  on BatchJobs'
    - name: PR labels 3
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      run: echo 'Test 3 pr label is  on bug'
    - name: get labels
      run: |
        echo "$LABELS" > labels.json
        cat labels.json
    - name: get action event
      run: |
        echo "$LABELS2"
