name: CI
on:
  pull_request:
    types: [ labeled, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PR labels
      if: ${{ github.event.label.name != 'BatchJobs' }}
      run: echo 'Test1 pr label is not on BatchJobs'
    - name:  query
      run: github.event.label > labels.json
    - name: display query
      run: tail -n 100 labels.json
    - name: test pr label
      if: ${{ github.event.label.name == 'BatchJobs' }}
      run: echo 'Test2 pr label is on BatchJobs'
