name: CI
on:
  pull_request:
    types: [ labeled, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PR labels `
      if: ${{ github.event.label.name != 'BatchJobs' }}
      run: echo 'Test1 pr label is not on BatchJobs'
    - name: PR labels 2
      if: ${{ github.event.label.name == 'BatchJobs' }}
      run: echo 'Test2 pr label is  on BatchJobs'
    - name: PR labels 2
      if: ${{ github.event.label.name[1] == 'bug' }}
      run: echo 'Test2 pr label is  on bug'
