name: UI tests
env:
  pr_number: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        run: 'curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/chendagit/aws/pulls/${{env.pr_number}} > pr_labels.json'
      - name: Show PR return result in JSON
        run: cat pr_labels.json
      - uses: actions/checkout@v2
      - name: run check PRs
        run: echo 'test'
