name: CI
on:
  pull_request:
    types: [ labeled, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PR labels 2
      if: contains(github.event.pull_request.labels.*.name, 'BatchJobs')
      run: echo 'Test 2 pr label is  on BatchJobs'
    - name: PR labels 3
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      run: echo 'Test 3 pr label is  on bug'
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
