name: Default
on:
  pull_request:
    types: [ unlabeled, synchronize ]
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, '')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PR unlabeled 1
      run: echo 'Test 1 pr unlabeled'
# test