name: CI
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PR labels 1
      if: ${{ github.event.label.name != 'BatchJobs' }}
      run: echo 'Test 1 pr label is not on BatchJobs'
    - name: PR labels 2
      if: ${{ github.event.label.name == 'BatchJobs' }}
      run: echo 'Test 2 pr label is  on BatchJobs'
    - name: PR labels 3
      if: ${{ github.event.label[1].name == 'bug' }}
      run: echo 'Test 3 pr label is  on bug'
    # - name: PR labels 2
    #   if: ${{ github.event.label.name[] == 'bug' }}
    #   run: echo 'Test2 pr label is  on all'
