name: CI
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    if: ${{ github.event.label.name == 'BatchJobs' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PR labels
      run: echo 'Test1 pr label is OK on BatchJobs'
    - name: test pr label
      run: echo 'Test2 pr label is OK on BatchJobs'
